### ISSUE TITLE
没有攒劲小曲我是不认可的

### ISSUE THREAD

**Issue by lottie-mg** [ProjectYinlan/Classic-StandOnTheStreet#5]
https://www.bilibili.com/video/BV1AY411i7Fz/?spm_id_from=333.337.search-card.all.click&vd_source=4daaee227cc430b96c9132d5828f3eb3

**Comment by nullqwertyuiop** [comment]
?

**Comment by yinlinghunjiang** [comment]
?

**Comment by colour93** [comment]
null 老师笑死我了

**Comment by nullqwertyuiop** [comment]
您好！

我们已近一周未收到您的补充信息，请原谅我们将此 issue 关闭。

如果您有任何补充信息，请不吝将此 issue 重新打开并回复，我们期待看到您的回复。
